def shared_pods
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '15.0'
  use_frameworks!
  # project 'Examples/LCEssentials.xcodeproj'

  # - Swift Essentials
  pod 'LCEssentials', :path => '../'
  #pod 'InputBarAccessoryView'
end

target 'LCEssentialsExample' do
  shared_pods
  
  post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        end
      end
    end
  end
end

